sudo: required
services: 
  - docker

before_install:
  - docker build -t dandocker1989/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dandocker1989/react-test npm test -- --coverage

after_success:
  - docker build -t dandocker1989/multi-client ./client
  - docker build -t dandocker1989/multi-nginx ./nginx
  - docker build -t dandocker1989/multi-server ./server
  - docker build -t dandocker1989/multi-worker ./worker

#Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dandocker1989/multi-client
  - docker push dandocker1989/multi-nginx
  - docker push dandocker1989/multi-server
  - docker push dandocker1989/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-654526538673
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
